### ISSUE TITLE
Missing Z values above initial cross sections

### ISSUE THREAD

**Issue by nicogodet** [CNR-Engineering/TatooineMesher#6]
Data to reproduce : [tatooine.zip](https://github.com/CNR-Engineering/TatooineMesher/files/14308547/tatooine.zip)

Command : 
```
cli\mesh_and_interpolate.py \
    --infile_constraint_lines constraint_lines.shp \
    --long_step 1 \
    --lat_step 1 \
    --attr_cross_sections sec_id \
    axe_cambo.shp \
    tatooine_input.shp \
    --outfile_nodes interpolate_points.shp \
    --interp_constraint_lines FINITE_DIFF
```

## What's the issue ?

In output file, interpolated point above initial cross sections are poplated with `nan` values.
![image](https://github.com/CNR-Engineering/TatooineMesher/assets/39594821/370aa41d-7ce1-44fb-8483-7acef783189d)
Which is annoying when rasterized
![image](https://github.com/CNR-Engineering/TatooineMesher/assets/39594821/41aa5600-ab2c-4753-8e14-22bbe9843ce5)

`tatooine_input.shp` was prepared by PreCourlis

**Comment by nicogodet** [comment]
Removing NULL values from input files seems to fix the issue

**Comment by lucduron** [comment]
Thank you for reporting this problem, but as identified it seems to be linked to the input data (NaN values).

**Comment by nicogodet** [comment]
Yep indeed, I forget to close this.
