### ISSUE TITLE
Allow use of Z values in axis to constraint lowest point in interpolation

### ISSUE THREAD

**Issue by nicogodet** [CNR-Engineering/TatooineMesher#7]
Some times, lowest point in bed river is surveyed (especially when distance between sections is high). This axis can catch pit and natural weir.

**Comment by lucduron** [comment]
Dear Nicolas,

The **thalweg** can be used in the _constraint lines file_ if you need.
The **hydraulic** axis can be the thalweg or another line, it is just used to order cross sections.

Regards,
Luc

**Comment by nicogodet** [comment]
Hi Luc, 

I admit I didn't test but does Z values of constraint lines are used during interpolation ?
I didn't go through the code to find this answer...

**Comment by lucduron** [comment]
The Z values of constraint lines are never used (Z is always interpolated from cross sections!), but the constraint lines forces the mesh and the interpolation to pass through specific point (the intersections between constraint lines and cross sections).
Mixing both sources (cross sections and constraint lines) for 3D interpolation seem complicated and hazardous to me.

**Comment by lucduron** [comment]
It seems safier and clearer to me to use cross sections for Z (and NOT in combinaison with constraint lines) and design constraint lines to pass exactly through specific location if needed (thalweg for example).
Does my explanations make it clearer?

**Comment by nicogodet** [comment]
I clearly understand the current logic (paper and wiki is quite clear, thank you for both !).

In reality, when there is a contraction of the bed river, this generally results in a deepening of the bed.
In public contract, price is often half the grade and we have to reduce the number of cross sections. It's quite often that we miss some locations where the bed is deeper than the linear interpolation between cross sections.
The survey of the talweg isn't quite expensive compared to a densification of surveyed cross sections and using Z value of the talweg could be a good workaround.

I don't know if my explaination is clear enough.

Currently, I always use talweg as constraint line.

For your info, I'm currently working on a qgis plugin to interact with tatooinemesher (I know the existence of PreCourlis but mine will allow more options and better output). I have made a development branch on my fork to facilitate the use of tatooine in python script (mostly moving the logic from cli script to dedicated function)).
You have done an amazing work here, I can finally drop HEC-RAS to interpolate sections.

**Comment by lucduron** [comment]
Happy to see that the work can be useful for the community!
